routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('signin/{provider}', 'Auth\LoginController@loginProviderUrl');
Route::get('signin/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('confirm/resend','Auth\RegisterController@resendConfirmation')->name('resend_confirmation');
Route::get('confirm/user/{token}','Auth\LoginController@confirmEmail')->name('confirmEmail');
Route::post('signup/getEmail','Auth\LoginController@setEmail')->name('set_email');

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('categories', 'Admin\CategoryController',['except' => ['create','edit','show']]);
    Route::resource('faculty', 'Admin\FacultyController',['except' => ['create','edit','show']]);

    Route::resource('colleges', 'Admin\CollegeController',['except' => ['create','edit','show']]);

    Route::get('classes/searchName', 'Admin\ClassController@searchByName')->name('classes.searchByName');
    Route::get('classes/searchCode', 'Admin\ClassController@searchByCode')->name('classes.searchByCode');
    Route::resource('classes', 'Admin\ClassController',['except' => ['create','store','edit','show']]);

    Route::get('bannerAds/expired', 'Admin\BannerAdController@expiredAds')->name('bannerAds.expiredAds');
    Route::resource('bannerAds', 'Admin\BannerAdController',['except' => ['create','show']]);

    Route::get('boxAds/expired', 'Admin\BoxAdController@expiredAds')->name('boxAds.expiredAds');
    Route::resource('boxAds', 'Admin\BoxAdController',['except' => ['create','show']]);

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');
    Route::post('test','Admin\AdminController@test')->name('test');

    Route::get('/','Admin\AdminController@index');
});

resources/views/admin/categories.blade.php
@extends('layouts.admin')

@section('body')
       
    <div class="content-body">
        <section id="addcategories">  
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title" ><a data-action="collapse"><h3>Faculties</h3><h6>Add, Edit or Remove Faculties</h6>  </a></div>
                            <a class="heading-elements-toggle">
                                <i class="icon-ellipsis font-medium-3"></i>
                            </a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body"> <!-- // collapse -->
                            <div class="card-block">
                                <div class="row col-md-12">
                                    <div style="padding-bottom:20px;">
                                        <form class="form" method="POST" action="{{ route('categories.store') }}">
                                            {{ csrf_field() }}
                                            <div class="row">
                                                <div class="form-body">
                                                    <div class="form-group col-sm-3">
                                                        <input type="text" class="form-control" placeholder="Add New Category" name="name" required>
                                                    </div>

                                                    <div class="form-group  col-sm-3">
                                                        <button type="submit" class="btn btn-primary">
                                                            <i class="icon-check2">Add Category</i> 
                                                        </button>
                                                    </div>  
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        @if(count($categories) == 0)
                                            <h6 style="text-align:  center;margin: 50px;">No category added yet.</h6>
                                        @else
                                            <div class="table-responsive ">
                                                
                                                <table class="table table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th style="width: 40%">Category</th>
                                                            <th style="width: 20%">Actions</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach($categories as $c)
                                                            <tr>
                                                                <td class="text-middle">
                                                                    <h4 id="categoryName{{ $c->id }}">{{$c->name}} </h4>
                                                                    
                                                                    <div id="CatupdateDiv{{$c->id}}" hidden>
                                                                        <form class="form" method="POST" action="{{ route('categories.update',$c->id) }}">
                                                                            <div class="row form-body">
                                                                                <div class="form-group col-sm-6">
                                                                                    {{csrf_field()}}
                                                                                    <input hidden name="_method" value="PATCH">

                                                                                    <input type="text" class="form-control" placeholder="Edit Name" name="name" value="{{ $c->name }}" required> 
                                                                                </div>
                                                                                <div class="form-group col-sm-6">
                                                                                    <button type="submit" class="btn btn-blue"> 
                                                                                        <i class="icon-check2"></i> 
                                                                                    </button>

                                                                                    <button class="btn btn-red" type="button" id="Catcancel{{ $c->id }}">
                                                                                        <i class="icon-cross"></i>
                                                                                    </button>          
                                                                                </div>
                                                                            </div> 
                                                                        </form>
                                                                    </div>
                                                                </td>
                                                            
                                                                <td class="text-middle">
                                                                    <a href="javascript:void(0)"  class="btn btn-outline-warning" style="" id="Catedit{{ $c->id }}">Edit</a>
                                                                
                                                                    <form action="{{ route('categories.destroy',$c->id) }}" method="POST" style="display:inline">
                                                                        {{ csrf_field() }}
                                                                        <input hidden name="_method" value="DELETE"/>
                                                                        <button type="button" id="deleteCat{{ $c->id }}" class="btn btn-outline-danger">Delete</button>
                                                                    </form>

                                                                </td>
                                                            </tr>
                                                        @endforeach
                                                    </tbody>
                                                </table>
                                                
                                            </div>
                                        @endif
                                        <div class="text-xs-center mb-3">
                                            <nav aria-label="Page navigation">
                                                {{ $categories->links() }}
                                            </nav>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection

@section('js')

<script type="text/javascript">
    $(document).ready(function() {
        $("[id*='Catedit']").click(function(){
            var id = $(this).attr("id").slice(7);
            $('#categoryName'+id).attr("hidden","true");
            $("#CatupdateDiv"+id).removeAttr("hidden");
        });

        $("[id*='Catcancel']").click(function(){
            var id = $(this).attr("id").slice(9);
            $('#categoryName'+id).removeAttr("hidden");
            $("#CatupdateDiv"+id).attr("hidden","true");
        });
    });
</script>
@endsection

resources/views/admin/colleges.blade.php
@extends('layouts.admin')

@section('body')
       
    <div class="content-body">
        <section id="addcolleges">  
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title" ><a data-action="collapse"><h3>Colleges</h3><h6>Add, Edit or Remove College Names</h6>  </a></div>
                            <a class="heading-elements-toggle">
                                <i class="icon-ellipsis font-medium-3"></i>
                            </a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body"> <!-- // collapse -->
                            <div class="card-block">
                                <div class="row col-md-12">
                                    <div style="padding-bottom:20px;">
                                        <form class="form" method="POST" action="{{ route('colleges.store') }}">
                                            {{ csrf_field() }}
                                            <div class="row">
                                                <div class="form-body">
                                                    <div class="form-group col-sm-3">
                                                        <input type="text" class="form-control" placeholder="Add New College" name="name" required>
                                                    </div>

                                                    <div class="form-group  col-sm-3">
                                                        <button type="submit" class="btn btn-primary">
                                                            <i class="icon-check2">Add College</i> 
                                                        </button>
                                                    </div>  
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        @if(count($colleges) == 0)
                                            <h6 style="text-align:  center;margin: 50px;">No college added yet.</h6>
                                        @else
                                            <div class="table-responsive ">
                                                
                                                <table class="table table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th style="width: 40%">College Name</th>
                                                            <th style="width: 20%">Actions</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach($colleges as $c)
                                                            <tr>
                                                                <td class="text-middle">
                                                                    <h4 id="collegeName{{ $c->id }}">{{$c->name}} </h4>
                                                                    
                                                                    <div id="ColupdateDiv{{$c->id}}" hidden>
                                                                        <form class="form" method="POST" action="{{ route('colleges.update',$c->id) }}">
                                                                            <div class="row form-body">
                                                                                <div class="form-group col-sm-6">
                                                                                    {{csrf_field()}}
                                                                                    <input hidden name="_method" value="PATCH">

                                                                                    <input type="text" class="form-control" placeholder="Edit Name" name="name" value="{{ $c->name }}" required> 
                                                                                </div>
                                                                                <div class="form-group col-sm-6">
                                                                                    <button type="submit" class="btn btn-blue"> 
                                                                                        <i class="icon-check2"></i> 
                                                                                    </button>

                                                                                    <button class="btn btn-red" type="button" id="Colcancel{{ $c->id }}">
                                                                                        <i class="icon-cross"></i>
                                                                                    </button>          
                                                                                </div>
                                                                            </div> 
                                                                        </form>
                                                                    </div>
                                                                </td>
                                                            
                                                                <td class="text-middle">
                                                                    <a href="javascript:void(0)"  class="btn btn-outline-warning" style="" id="Coledit{{ $c->id }}">Edit</a>
                                                                
                                                                    <form action="{{ route('colleges.destroy',$c->id) }}" method="POST" style="display:inline">
                                                                        {{ csrf_field() }}
                                                                        <input hidden name="_method" value="DELETE"/>
                                                                        <button type="button" id="deleteCol{{ $c->id }}" class="btn btn-outline-danger">Delete</button>
                                                                    </form>

                                                                </td>
                                                            </tr>
                                                        @endforeach
                                                    </tbody>
                                                </table>
                                                
                                            </div>
                                        @endif
                                        <div class="text-xs-center mb-3">
                                            <nav aria-label="Page navigation">
                                                {{ $colleges->links() }}
                                            </nav>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection

@section('js')

<script type="text/javascript">
    $(document).ready(function() {
        $("[id*='Coledit']").click(function(){
            var id = $(this).attr("id").slice(7);
            $('#collegeName'+id).attr("hidden","true");
            $("#ColupdateDiv"+id).removeAttr("hidden");
        });

        $("[id*='Colcancel']").click(function(){
            var id = $(this).attr("id").slice(9);
            $('#collegeName'+id).removeAttr("hidden");
            $("#ColupdateDiv"+id).attr("hidden","true");
        });
    });
</script>
@endsection

resources/views/admin/testimonials.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Testimonials</h2>
        </div>
    </div>
    <div class="row match-height">
        <div class="col-xl-4 col-md-6 col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-block">
                    @if($state == 'Add')
                        <form class="form" method="POST" action="{{ route('testimonials.store') }}"  enctype="multipart/form-data">
                    @else
                        <form class="form" method="POST" action="{{ route('testimonials.update',$testimonial_->id) }}"  enctype="multipart/form-data">                            
                        <input type="hidden" name="_method" value="PATCH" >
                    @endif
                            {{ csrf_field() }}
                            
                            <div class="form-group">
                                <label for="name"><strong>Name:</strong></label>
                                @if ($errors->has('name'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                @endif
                                <input type="text" id="name" class="form-control" name="name" value="{{ $testimonial_->name }}" required/>
                            </div>

                            <div class="form-group">
                                <label for="profession"><strong>Profession:</strong></label>
                                @if ($errors->has('profession'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('profession') }}</strong>
                                    </div>
                                @endif
                                <input type="text" id="profession" class="form-control" name="profession" value="{{ $testimonial_->profession }}" required/>
                            </div>

                            <div class="form-group">
                                <label for="photo"><strong>{{ $state=='Add'?'':'Current ' }}Image <span class="text-muted">(Optional)</span>: </strong></label> {{ $testimonial_->photo }}
                                @if ($errors->has('photo'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('photo') }}</strong>
                                    </div>
                                @endif
                                <input type="file" id="photo" class="form-control" name="photo"/>
                            </div>
                            <div class="form-group">
                                <label><strong>New Testimonial:</strong></label>
                                @if ($errors->has('content'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('content') }}</strong>
                                    </div>
                                @endif
                            
                                <textarea class="form-control" rows='6' id="content" name="content" required>{{ $testimonial_->content }}</textarea>

                            </div>
                            <div class="form-actions right">
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon-check2"></i> {{ $state=="Add"?"Add New":"Save" }}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @foreach($testimonials as $testimonial)
            <div class="col-xl-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-block">
                            <h4 class="card-title">{{ $testimonial->name }}</h4>
                            <h6 class="card-subtitle text-muted">{{ $testimonial->profession }}</h6>
                            @if($testimonial->photo)
                                <img class="img-fluid my-1" src="{{ route('asset', ['landing_images',$testimonial->photo,290,290]) }}" alt="Card image cap">
                            @else
                                <img class="img-fluid my-1" src="{{ route('asset2', ['img','avatar.png','png',290,290]) }}" alt="{{ $testimonial->name }}"/>
                            @endif
                            <p class="card-text">{{ $testimonial->content }}</p>

                            <a href="{{ route('testimonials.edit',$testimonial->id) }}" class="btn btn-outline btn-warning">Edit</a>
                            
                            <form action="{{ route('testimonials.destroy',$testimonial->id) }}" style="display:inline" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE" >
                                <button id='deleteTestimonial' type="button" class="btn btn-outline btn-danger">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection