routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('signin/{provider}', 'Auth\LoginController@loginProviderUrl');
Route::get('signin/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('confirm/resend','Auth\RegisterController@resendConfirmation')->name('resend_confirmation');
Route::get('confirm/user/{token}','Auth\LoginController@confirmEmail')->name('confirmEmail');
Route::post('signup/getEmail','Auth\LoginController@setEmail')->name('set_email');

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('categories', 'Admin\CategoryController',['except' => ['create','edit','show']]);
    Route::resource('faculty', 'Admin\FacultyController',['except' => ['create','edit','show']]);

    Route::resource('colleges', 'Admin\CollegeController',['except' => ['create','edit','show']]);

    Route::get('classes/searchName', 'Admin\ClassController@searchByName')->name('classes.searchByName');
    Route::get('classes/searchCode', 'Admin\ClassController@searchByCode')->name('classes.searchByCode');
    Route::resource('classes', 'Admin\ClassController',['except' => ['create','store','edit','show']]);

    Route::get('bannerAds/expired', 'Admin\BannerAdController@expiredAds')->name('bannerAds.expiredAds');
    Route::resource('bannerAds', 'Admin\BannerAdController',['except' => ['create','show']]);

    Route::get('boxAds/expired', 'Admin\BoxAdController@expiredAds')->name('boxAds.expiredAds');
    Route::resource('boxAds', 'Admin\BoxAdController',['except' => ['create','show']]);

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');
    Route::post('test','Admin\AdminController@test')->name('test');

    Route::get('/','Admin\AdminController@index');
});

app/Http/Controllers/Admin/BannerAdController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\BannerAd;
use App\Category;
use App\Faculty;
use App\Drive;
use App\Drive_ad;
use Carbon\Carbon;

class BannerAdController extends Controller
{
    public function __construct(Request $request)
    {
        $this->middleware('auth:admin_user');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ads = BannerAd::orderBy('updated_at','desc')->paginate(10);
        $cats = Faculty::orderBy('name','asc')->get(); //only if it has class
        $categories = [];
        
        foreach($cats as $c){
            $category['cat'] = $c;

            $all_ids=Drive::where('faculty_id',$c->id)->pluck('id');
            $used_ids=Drive_ad::pluck('id');
            $free_ids=$all_ids->diff($used_ids);

            $category['count'] = $free_ids->count();
            // $category['count'] = $c->classes()->where('banner_ad_id',null)->count();
            $categories []= $category;
            
        }
        
        return view('admin.bannerads.index')->with('ads',$ads)->with('categories',$categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'title'=>'required',
            'category' => 'required|exists:faculties,id'
        ]);

        $all_ids=Drive::where('faculty_id',$request->category)->pluck('id');
        $used_ids=Drive_ad::pluck('id');
        $free_ids=$all_ids->diff($used_ids);
        // $max_qty = Category::find($request->category)->classes->count();
        $max_qty = $free_ids->count();

        $request->validate([
            
            'quantity' => 'required|numeric|min:1|max:'.$max_qty,
            'link' => 'required|url',
            'expiry_date' => 'required|date|after:today',
            'image' => 'required|image'
        ]);
        
        $ad = new BannerAd;
        $ad->title=$request->title;
        $ad->faculty_id = $request->category;
        $ad->quantity = $request->quantity;
        $ad->link = $request->link;
        $ad->expiry_date = $request->expiry_date;

        if($request->hasFile('image')){
            $photo = $request->file('image');
            $filename = $photo->getClientOriginalName();
            $location = public_path('bannerad_images/');
            $photo->move($location,$filename);
            $ad->image = $filename;
        }
        $ad->save();
        $drive_ids=Drive::where('faculty_id',$request->category)->pluck('id');
        $used_ids=Drive_ad::all()->pluck('id');

        $diff=$drive_ids->diff($used_ids)->shuffle()->take($ad->quantity);
        
        foreach($diff as $d)
        {
            $drive_ad= new Drive_ad;
            $drive_ad->id=$d;
            $drive_ad->banner_ads_id=$ad->id;
            $drive_ad->save();
        }

        

        /*
            $classes = Drive::where('category_id',$ad->category_id)->where('banner_ad_id',null)->random($quantity); //with null ad_id

            foreach($classes as $class){
                $class->banner_ad_id = $ad->id;
                $class->save();
            }
        */

        $request->session()->flash('success', 'Banner Ad successfully added.');        
        
        return redirect()->route('bannerAds.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ad = BannerAd::findOrFail($id);

        $cats = Faculty::orderBy('name','asc')->get(); //only if it has class
        $categories = [];
        
        foreach($cats as $c){
            $category['cat'] = $c;

            $all_ids=Drive::where('faculty_id',$c->id)->pluck('id');
            $used_ids=Drive_ad::pluck('id');
            $free_ids=$all_ids->diff($used_ids);

            $category['count'] = $free_ids->count();
            // $category['count'] = $c->classes()->where('banner_ad_id',null)->count();
            $categories []= $category;
            
        }
        
        return view('admin.bannerads.edit')->with('ad',$ad)->with('categories',$categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'title'=>'required',
            'link' => 'required|url',
            'expiry_date' => 'required|date|after:today',
            'image' => 'nullable|mimes:jpeg,jpg,png,gif|max:100000'
        ]);
        
        $ad = BannerAd::findOrFail($id);
        $ad->title=$request->title;
        $ad->link = $request->link;
        $ad->expiry_date = $request->expiry_date;

        if($request->hasFile('image')){
            unlink(public_path('bannerad_images/'.$ad->image));
            $photo = $request->file('image');
            $filename = $photo->getClientOriginalName();
            $location = public_path('bannerad_images/');
            $photo->move($location,$filename);
            $ad->image = $filename;
        }
        $ad->save();

        $request->session()->flash('success', 'Banner Ad successfully updated.');        
        
        return redirect()->route('bannerAds.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $ad = BannerAd::findOrFail($id);

        unlink(public_path('bannerad_images/'.$ad->image));
        $ad->delete();
        
        $request->session()->flash('success', 'Banner Ad successfully deleted.');        
        
        return redirect()->route('bannerAds.index');
    }

    public function expiredAds(){
        $date = Carbon::today();  
        $ads = BannerAd::where('expiry_date','<',$date)->orderBy('updated_at','desc')->paginate(10);

        return view('admin.bannerads.result')->with('ads',$ads);
    }
}

resources/views/admin/bannerads/index.blade.php
@extends('layouts.admin')

@section('body')
<style>
    .btn-file {
        position: relative;
        overflow: hidden;
    }
    .btn-file input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        outline: none;
        background: white;
        cursor: inherit;
        display: block;
    }
    
    #img-upload{
        height:30%;
        width: 30%;
        text-align: center;
        padding-top:10px;
        }
</style>

    <div class="content-body">
        <section>  
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title" ><a data-action="collapse"><button  class="btn btn-md btn-primary"><i class=" {{ count($errors)>0 ? 'icon-minus4' : 'icon-plus4' }}" aria-hidden="true"></i> Add Banner Ads</button></a></h4>
                            <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class=" {{ count($errors)>0 ? 'icon-minus4' : 'icon-plus4' }}"></i></a></li>
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                            
                        <div class="card-body collapse {{ count($errors)>0 ? 'in' : '' }}">                  
                            <div class="card-block ">
                                <form class="form" method="POST" action="{{route('bannerAds.store')}}" enctype="multipart/form-data">
                                    {{csrf_field()}}
                                    <div class="row">
                                        <div class="form-body">
                                            <div class="form-group col-sm-12">
                                                <label for="link">Title</label>
                                                <input type="text" id="title" class="form-control" placeholder="Title of ad" name="title" value="{{old('title')}}" required>
                                            </div>
                                            <div class="form-group col-sm-12">
                                                <label for="category">Category</label>
                                                <select id="category" class="form-control" name="category" required>
                                                    <option data-count="1" selected disabled>Choose a category</option>
                                                    @foreach($categories as $c)
                                                        <option data-count="{{ $c['count'] }}" value="{{ $c['cat']->id }}"  {{ old('category') == $c['cat']->id ? 'selected' : '' }}>{{ $c['cat']->name }} - Available {{ $c['count'] }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            
                                            <div class="form-group col-sm-12">
                                                <label for="quantity">Quantity</label>
                                                <input placeholder="Quantity" type="number" class="form-control" id="quantity" min="1" max="1" name="quantity"  value="{{old('quantity')}}" required/>
                                            </div>

                                            <div class="form-group col-sm-12">
                                                <label for="link">Link</label>
                                                <input type="text" id="link" class="form-control" placeholder="Link - http://www." name="link" value="{{old('link')}}" required>
                                            </div>
                                            
                                            <div class="form-group col-sm-12">
                                                <label for="timesheetinput3">Expiry Date</label>
                                                <div class="position-relative has-icon-left">
                                                    <input type="date" id="timesheetinput3" class="form-control" value="{{old('expiry_date')}}" name="expiry_date" required>
                                                    <div class="form-control-position">
                                                        <i class="icon-calendar5"></i>
                                                    </div>
                                                </div>
                                            </div>  
                                            <div class="row col-sm-12">
                                                <div class="form-group col-sm-6" style="margin-bottom:0px;">
                                                    <label>Upload Image</label>
                                                    <div class="input-group">
                                                        <span class="input-group-btn">
                                                            <span class="btn btn-primary btn-file">
                                                                Browse images… <input type="file" name="image" id="imgInp" required>
                                                            </span>
                                                        </span>
                                                        <input type="text" class="form-control" name="image" readonly>
                                                    </div>
                                                    <img style="padding-bottom: 15px;" id='img-upload'/>
                                                </div>
                                            </div>
            
                                            <div class="form-group col-sm-12">
                                                <button type="submit" class="btn btn-md btn-success" id="add">
                                                    <i class="icon-check2">Add</i> 
                                                </button>
                                            </div>  
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div style="float:right">
            <a href="{{ route('bannerAds.expiredAds') }}" class="btn btn-md btn-primary mb-1">See Expired Ads</a>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"><a data-action="collapse"> Banner Ads</a></h4>
                        <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                                <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-body collapse in">
                        @if(count($ads) == 0)
                            <h6 style="text-align:  center;margin: 50px;">No banner ads added yet.</h6>
                        @else
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                        <tr>
                                            <th>S.N</th>
                                            <th>Title</th>
                                            <th>Category</th>
                                            <th>Quantity</th>
                                            <th>Image</th>
                                            <th>Expiry Date</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($ads as $ad)
                                            <tr>
                                                <td>{{ $loop->iteration * $ads->currentPage() }}</td>
                                                <td>{{ $ad->title }}</td>
                                                <td>{{ $ad->faculty->name }}</td>
                                                <td>{{ $ad->quantity }}</td>
                                                <td><a href="{{ $ad->link }}" target="_blank" title="{{ $ad->link }}"><img src="{{ asset('bannerad_images/'.$ad->image) }}" width="50px" height="50px"/></a></td>
                                                <td>{{ date('M j,Y',strtotime($ad->expiry_date)) }}</td>
                                                <td>
                                                    <a href="{{ route('bannerAds.edit',$ad->id) }}" class="btn btn-sm btn-primary">Edit</a>
                                                    <form action="{{ route('bannerAds.destroy',$ad->id) }}" method="POST" style="display:inline">
                                                        {{ csrf_field() }}
                                                        <input type="hidden" name="_method" value="DELETE"/>
                                                        <button type="button" id="deleteAd{{$ad->id}}" class="btn btn-sm btn-danger">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach   
                                    </tbody>
                                </table>
                            </div>
                        @endif
                        <div class="text-xs-center mb-3">
                            <nav aria-label="Page navigation">
                                {{ $ads->links() }}
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
    <script>
        $(document).ready( function() {
            var max = $('#category').find(":selected").attr('data-count');
            $('#quantity').attr('max',max);

            $(document).on('change', '.btn-file :file', function() {
                var input = $(this),
                label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                input.trigger('fileselect', [label]);
            });
    
            $('.btn-file :file').on('fileselect', function(event, label) {
                
                var input = $(this).parents('.input-group').find(':text'),
                    log = label;
                
                if( input.length ) {
                    input.val(log);
                } else {
                    if( log ) alert(log);
                }
            
            });
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    
                    reader.onload = function (e) {
                        $('#img-upload').attr('src', e.target.result);
                    }
                    
                    reader.readAsDataURL(input.files[0]);
                }
            }
    
            $("#imgInp").change(function(){
                readURL(this);
            }); 

            $('#category').on('change',function(){
                max = $(this).find(":selected").attr('data-count');
                $('#quantity').attr('max',max);
            });	
        });
    </script>


@endsection

resources/views/admin/bannerads/result.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-body">
        <section>  
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title" ><a data-action="collapse">Results for Banner Ads</a></h4>
                            <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a href="{{ route('bannerAds.index') }}"><i class="icon-arrow-left"></i></a></li>
                                    <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                            
                        <div class="card-body collapse in">                    
                            @if(count($ads) == 0)
                                <h6 style="text-align:  center;margin: 50px;">No expired banner ads.</h6>
                            @else
                                <div class="table-responsive">
                                    <table class="table mb-0">
                                        <thead>
                                            <tr>
                                                <th>S.N</th>
                                                <th>Category</th>
                                                <th>Quantity</th>
                                                <th>Image</th>
                                                <th>Expiry Date</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($ads as $ad)
                                                <tr>
                                                    <td>{{ $loop->iteration * $ads->currentPage() }}</td>
                                                    <td>{{ $ad->category->name }}</td>
                                                    <td>{{ $ad->quantity }}</td>
                                                    <td><a href="{{ $ad->link }}" target="_blank" title="{{ $ad->link }}"><img src="{{ asset('bannerad_images/'.$ad->image) }}" width="50px" height="50px"/></a></td>
                                                    <td>{{ date('M j,Y',strtotime($ad->expiry_date)) }}</td>
                                                    <td>
                                                        <a href="{{ route('bannerAds.edit',$ad->id) }}" class="btn btn-sm btn-primary">Edit</a>
                                                        <form action="{{ route('bannerAds.destroy',$ad->id) }}" method="POST" style="display:inline">
                                                            {{ csrf_field() }}
                                                            <input type="hidden" name="_method" value="DELETE"/>
                                                            <button type="button" id="deleteAd{{$ad->id}}" class="btn btn-sm btn-danger">Delete</button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach   
                                        </tbody>
                                    </table>
                                </div>
                            @endif
                            <div class="text-xs-center mb-3">
                                <nav aria-label="Page navigation">
                                    {{ $ads->links() }}
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection