routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('signin/{provider}', 'Auth\LoginController@loginProviderUrl');
Route::get('signin/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('confirm/resend','Auth\RegisterController@resendConfirmation')->name('resend_confirmation');
Route::get('confirm/user/{token}','Auth\LoginController@confirmEmail')->name('confirmEmail');
Route::post('signup/getEmail','Auth\LoginController@setEmail')->name('set_email');

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('categories', 'Admin\CategoryController',['except' => ['create','edit','show']]);
    Route::resource('faculty', 'Admin\FacultyController',['except' => ['create','edit','show']]);

    Route::resource('colleges', 'Admin\CollegeController',['except' => ['create','edit','show']]);

    Route::get('classes/searchName', 'Admin\ClassController@searchByName')->name('classes.searchByName');
    Route::get('classes/searchCode', 'Admin\ClassController@searchByCode')->name('classes.searchByCode');
    Route::resource('classes', 'Admin\ClassController',['except' => ['create','store','edit','show']]);

    Route::get('bannerAds/expired', 'Admin\BannerAdController@expiredAds')->name('bannerAds.expiredAds');
    Route::resource('bannerAds', 'Admin\BannerAdController',['except' => ['create','show']]);

    Route::get('boxAds/expired', 'Admin\BoxAdController@expiredAds')->name('boxAds.expiredAds');
    Route::resource('boxAds', 'Admin\BoxAdController',['except' => ['create','show']]);

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');
    Route::post('test','Admin\AdminController@test')->name('test');

    Route::get('/','Admin\AdminController@index');
});

app/Http/Controllers/Admin/BoxAdController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\BoxAd;
use App\Faculty;
use App\College;
use Carbon\Carbon;

class BoxAdController extends Controller
{
    
    public function __construct(Request $request)
    {
        $this->middleware('auth:admin_user');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ads = BoxAd::orderBy('updated_at','desc')->paginate(10);
        $faculties = Faculty::orderBy('name','asc')->get(); //only if it has class
        
        $colleges = College::orderBy('name','asc')->get(); //''
        return view('admin.boxads.index')->with('ads',$ads)->with('faculties',$faculties)->with('colleges',$colleges);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'target' => 'required|in:Teacher,Student,Both',
            'faculty.*' => 'required|exists:faculties,id',
            'college.*' => 'required|exists:colleges,id',
            'year.*' => 'required|in:Current,Pass Out',
            'link' => 'required|url',
            'expiry_date' => 'required|date|after:today',
            'content' => 'required'
        ]);
        
        $ad = new BoxAd;
        $ad->target = $request->target;
        $ad->year = json_encode($request->year);
        $ad->link = $request->link;
        $ad->expiry_date = $request->expiry_date;
        $ad->content=$request->content;
        $ad->save();

        $ad->faculties()->attach($request->faculty);
        $ad->colleges()->attach($request->college);

        $request->session()->flash('success', 'Box Ad successfully added.');        
        
        return redirect()->route('boxAds.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ad = BoxAd::findOrFail($id);

        $faculties= Faculty::orderBy('name','asc')->get();
        $colleges = College::orderBy('name','asc')->get();

        return view('admin.boxads.edit')->with('ad',$ad)->with('faculties',$faculties)->with('colleges',$colleges);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'target' => 'required|in:Teacher,Student,Both',
            'faculty.*' => 'required|exists:faculties,id',
            'college.*' => 'required|exists:colleges,id',
            'year.*' => 'required|in:Current,Pass Out',
            'link' => 'required|url',
            'expiry_date' => 'required|date|after:today',
            'content' => 'required'
        ]);
        
        $ad = BoxAd::findOrFail($id);
        $ad->target = $request->target;
        $ad->year = json_encode($request->year);
        $ad->link = $request->link;
        $ad->expiry_date = $request->expiry_date;
        $ad->content=$request->content;
        
        $ad->save();

        $ad->faculties()->sync($request->faculty);
        $ad->colleges()->sync($request->college);

        $request->session()->flash('success', 'Box Ad successfully updated.');        
        
        return redirect()->route('boxAds.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $ad = BoxAd::findOrFail($id);

        unlink(public_path('boxad_images/'.$ad->image));
        $ad->delete();
        
        $request->session()->flash('success', 'Box Ad successfully deleted.');        
        
        return redirect()->route('boxAds.index');
    }

    public function expiredAds(){
        $date = Carbon::today();  
        $ads = BoxAd::where('expiry_date','<',$date)->orderBy('updated_at','desc')->paginate(10);

        return view('admin.boxads.result')->with('ads',$ads);
    }
}

resources/views/admin/boxads/edit.blade.php
@extends('layouts.admin')

@section('body')
<style>
    .btn-file {
        position: relative;
        overflow: hidden;
    }
    .btn-file input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        outline: none;
        background: white;
        cursor: inherit;
        display: block;
    }
    
    #img-upload{
        height:30%;
        width: 30%;
        text-align: center;
        padding-top:10px;
        }
</style>
<link href="{{ asset('admin-assets/select2.css') }}" rel="stylesheet" />

    <div class="content-body">
        <section>  
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title" ><a data-action="collapse"><button  class="btn btn-md btn-primary"><i class="icon-minus4" aria-hidden="true"></i> Edit Box Ads</button></a></h4>
                            <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a href="{{ route('boxAds.index') }}"><i class="icon-arrow-left"></i></a></li>
                                    <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                            
                        <div class="card-body collapse in">
                            <div class="card-block ">
                                <form class="form" method="POST" action="{{route('boxAds.update',$ad->id)}}" enctype="multipart/form-data">
                                    {{csrf_field()}}
                                    <input type="hidden" name="_method" value="PATCH"/>
                                    <div class="row">
                                        <div class="form-body ">
                                            <div class="form-group col-sm-12">
                                                <label>Target</label>
                                                <div class="input-group">
                                                    <label class="display-inline-block custom-control custom-radio ml-1">
                                                        <input type="radio" name="target" value="Teacher" {{ $ad->target == 'Teacher' ? 'checked' : '' }} class="custom-control-input">
                                                        <span class="custom-control-indicator"></span>
                                                        <span class="custom-control-description ml-0">Teacher</span>
                                                    </label>
                                                    <label class="display-inline-block custom-control custom-radio">
                                                        <input type="radio" name="target" value="Student" {{ $ad->target == 'Student' ? 'checked' : '' }} class="custom-control-input">
                                                        <span class="custom-control-indicator"></span>
                                                        <span class="custom-control-description ml-0">Student</span>
                                                    </label>
                                                    <label class="display-inline-block custom-control custom-radio">
                                                        <input type="radio" name="target" value="Both" {{ $ad->target == 'Both' ? 'checked' : '' }} class="custom-control-input">
                                                        <span class="custom-control-indicator"></span>
                                                        <span class="custom-control-description ml-0">Both</span>
                                                    </label>
                                                </div>
                                            </div>

                                            <div class="form-group col-sm-12">
                                                <label for="selectfaculties">Faculty</label>
                                                <?php $cats = $ad->faculties()->pluck('faculties.id')->toArray(); ?>
                                                <select id="selectfaculties" class="form-control" name="faculty[]" class="js-example-basic-multiple" multiple="multiple" width="100%">
                                                    @foreach($faculties as $c)
                                                        <option value="{{ $c->id }}"  {{ in_array($c->id,$cats) ? 'selected' : '' }}>{{ $c->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            
                                            <div class="form-group col-sm-12">
                                                <label for="selectcolleges">College</label>
                                                <?php $colgs = $ad->colleges()->pluck('colleges.id')->toArray(); ?>
                                                <select id="selectcolleges" class="form-control" name="college[]" class="js-example-basic-multiple" multiple="multiple" width="100%">
                                                    @foreach($colleges as $c)
                                                        <option value="{{ $c->id }}"  {{ in_array($c->id,$colgs) ? 'selected' : '' }}>{{ $c->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>

                                            <div class="form-group col-sm-12">
                                                <label>Year</label>
                                                <div class="input-group">
                                                    <label class="display-inline-block custom-control custom-radio ml-1">
                                                        <input type="checkbox" name="year[]" value="Current" {{ in_array('Current',json_decode($ad->year)) ? 'checked' : '' }} class="chk-remember">
                                                        <span class="custom-control-description ml-0">Current</span>
                                                    </label>
                                                    <label class="display-inline-block custom-control custom-radio">
                                                        <input type="checkbox" name="year[]" value="Pass Out" {{ in_array('Pass Out',json_decode($ad->year)) ? 'checked' : '' }} class="chk-remember">
                                                        <span class="custom-control-description ml-0">Pass Out</span>
                                                    </label>
                                                </div>
                                            </div>

                                            <div class="form-group col-sm-12">
                                                <label for="link">Link</label>
                                                <input type="text" id="link" class="form-control" placeholder="Link - http://www." name="link" value="{{ $ad->link }}" required>
                                            </div>
                                            
                                            <div class="form-group col-sm-12">
                                                <label for="timesheetinput3">Expiry Date</label>
                                                <div class="position-relative has-icon-left">
                                                    <input type="date" id="timesheetinput3" class="form-control" value="{{ $ad->expiry_date }}" name="expiry_date" required>
                                                    <div class="form-control-position">
                                                        <i class="icon-calendar5"></i>
                                                    </div>
                                                </div>
                                            </div>  
                                            <div class="row col-sm-12">
                                                <div class="form-group">
                                                    <label for="projectinput8">Content</label>
                                                <textarea id="projectinput8" rows="5" class="form-control" name="content" placeholder="Ad content">{{$ad->content}}</textarea>
                                                </div>
                                            </div>
            
                                            <div class="form-group col-sm-12">
                                                <button type="submit" class="btn btn-md btn-success" id="add">
                                                    <i class="icon-check2">Save</i> 
                                                </button>
                                            </div>  
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection

@section('js')
    <script src="{{ asset('admin-assets/select2.js') }}"></script>
   
    <script>
        $(document).ready( function() {
            $(document).on('change', '.btn-file :file', function() {
                var input = $(this),
                label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                input.trigger('fileselect', [label]);
            });
    
            $('.btn-file :file').on('fileselect', function(event, label) {
                
                var input = $(this).parents('.input-group').find(':text'),
                    log = label;
                
                if( input.length ) {
                    input.val(log);
                } else {
                    if( log ) alert(log);
                }
            
            });
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    
                    reader.onload = function (e) {
                        $('#img-upload').attr('src', e.target.result);
                    }
                    
                    reader.readAsDataURL(input.files[0]);
                }
            }
    
            $("#imgInp").change(function(){
                readURL(this);
            });

            $('#selectfaculties').select2({
                placeholder: "Select faculties",
                width: '100%',
                height: '45px',
                escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
                
            });

            $('#selectcolleges').select2({
                placeholder: "Select College Names",
                width: '100%',
                height: '45px',
                escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
                
            }); 	
        });
    </script>


@endsection

resources/views/admin/boxads/result.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-body">
        <section>  
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title" ><a data-action="collapse">Results for Box Ads</a></h4>
                            <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a href="{{ route('boxAds.index') }}"><i class="icon-arrow-left"></i></a></li>
                                    <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                            
                        <div class="card-body collapse in">                    
                            @if(count($ads) == 0)
                                <h6 style="text-align:  center;margin: 50px;">No expired box ads.</h6>
                            @else
                                <div class="table-responsive">
                                    <table class="table mb-0">
                                        <thead>
                                            <tr>
                                                <th>S.N</th>
                                                <th>Target</th>
                                                <th>Categories</th>
                                                <th>Colleges</th>
                                                <th>Year</th>
                                                <th>Image</th>
                                                <th>Expiry Date</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($ads as $ad)
                                                <tr>
                                                    <td>{{ $loop->iteration * $ads->currentPage() }}</td>
                                                    <td>{{ $ad->target }}</td>
                                                    <td>
                                                        @foreach($ad->categories as $c)
                                                            <div class="tag tag-info" style="margin:2px">{{ $c->name }}</div>
                                                        @endforeach
                                                    </td>
                                                    <td>
                                                        @foreach($ad->colleges as $c)
                                                            <div class="tag tag-success" style="margin:2px">{{ $c->name }}</div>
                                                        @endforeach
                                                    </td>
                                                    <td>
                                                        @foreach(json_decode($ad->year) as $c)
                                                            <div class="tag tag-default" style="margin:2px">{{ $c }}</div>
                                                        @endforeach
                                                    </td>
                                                    <td><a href="{{ $ad->link }}" target="_blank" title="{{ $ad->link }}"><img src="{{ asset('boxad_images/'.$ad->image) }}" width="50px" height="50px"/></a></td>
                                                    <td>{{ date('M j,Y',strtotime($ad->expiry_date)) }}</td>
                                                    <td>
                                                        <a href="{{ route('boxAds.edit',$ad->id) }}" class="btn btn-sm btn-primary">Edit</a>
                                                        <form action="{{ route('boxAds.destroy',$ad->id) }}" method="POST" style="display:inline">
                                                            {{ csrf_field() }}
                                                            <input type="hidden" name="_method" value="DELETE"/>
                                                            <button type="button" id="deleteAd{{$ad->id}}" class="btn btn-sm btn-danger">Delete</button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach   
                                        </tbody>
                                    </table>
                                </div>
                            @endif
                            <div class="text-xs-center mb-3">
                                <nav aria-label="Page navigation">
                                    {{ $ads->links() }}
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection